
POST http://localhost:3000/regAdmin
Content-Type: application/json

{
    "username":"Admin1",
    "password":"1234",
    "name":"Boss",
    "email":"Boss@gmail.com",
    "phoneNumber":"0123456789",
    "role":"Admin"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"Admin1",
    "password":"1234"
}

###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNTQ3OTE3ODFmZDc3NDk4MDQwNGIiLCJ1c2VybmFtZSI6IkFkbWluMSIsInBhc3N3b3JkIjoiJDJiJDEwJC5yYzRKN3Mzd05Vd21NWGxIZFI0Ry5PUGpkSHk3bEwwT0lrRXNCU1NYVms5NmFDcHE3SEsyIiwibmFtZSI6IkJvc3MiLCJlbWFpbCI6IkJvc3NAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIwMTIzNDU2Nzg5Iiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzAzMTgzNDQ1LCJleHAiOjE3MDMxODcwNDV9.dJ6bkBlG4esr6LaF0vP8qru1XjENFT1aowpzYWSmxkE
Content-Type: application/json

{ 
    "username":"Secure2",
    "password":"1234",
    "name":"Security1",
    "email":"Securityq@gmail.com"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"Secure2",
    "password":"1234"
}

###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNTRiNjE3ODFmZDc3NDk4MDQwNGMiLCJ1c2VybmFtZSI6IlNlY3VyZTIiLCJwYXNzd29yZCI6IiQyYiQxMCRsNkZmY2dERGguam1mWThReFJFWTJlcEFGaE0yU09aMUg0djlQdTlNcWRuclkzSzR6RllRNiIsIm5hbWUiOiJTZWN1cml0eTEiLCJlbWFpbCI6IlNlY3VyaXR5cUBnbWFpbC5jb20iLCJyb2xlIjoiU2VjdXJpdHkiLCJ2aXNpdG9ycyI6WyJhaG1hZDIxIl0sImlhdCI6MTcwMzE4MzYxOCwiZXhwIjoxNzAzMTg3MjE4fQ.RKTW12PyWKZooBVACPyc4V8HoFibszzZLgzcixuEO78
Content-Type: application/json

{   
    "username":"daus",
    "password":"1234",
    "name": "Firdaus",
    "ic": "020809-10-0323",   
    "phone": "01124303790", 
    "vehicleNo": "JRP 3465",
    "department": "ftkmp",
    "company": "MPP.Enterprise",
    "date" : "15/06/2023"
}
###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDlhNTRiNjE3ODFmZDc3NDk4MDQwNGMiLCJ1c2VybmFtZSI6IlNlY3VyZTIiLCJwYXNzd29yZCI6IiQyYiQxMCRsNkZmY2dERGguam1mWThReFJFWTJlcEFGaE0yU09aMUg0djlQdTlNcWRuclkzSzR6RllRNiIsIm5hbWUiOiJTZWN1cml0eTEiLCJlbWFpbCI6IlNlY3VyaXR5cUBnbWFpbC5jb20iLCJyb2xlIjoiU2VjdXJpdHkiLCJ2aXNpdG9ycyI6WyJhaG1hZDIxIl0sImlhdCI6MTcwMzE4MzYxOCwiZXhwIjoxNzAzMTg3MjE4fQ.RKTW12PyWKZooBVACPyc4V8HoFibszzZLgzcixuEO78
Content-Type: application/json

{   
    "username":"ahmad21",
    "password":"1234",
    "name": "Ahmad",
    "ic": "020534-01-0092",   
    "phone": "01124303790", 
    "vehicleNo": "JRP 3465",
    "department": "ftkmp",
    "company": "MPP.Enterprise",
    "date" : "15/06/2023"
}
###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"daus",
    "password":"1234"
}
###
PATCH http://localhost:3000/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTFiODlmZDkwZWFlNzBjNDRmNTUiLCJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IiQyYiQxMCRWc0wxeWpiNGUxSUJicTRPaTlEUnpPVHQzSFFRdmxTTFFabzBISi8yR1E4NXRGcjJlV3JBMiIsIm5hbWUiOiJGaXJkYXVzIiwiaWMiOiIwMjA4MDktMTAtMDMyMyIsImVtYWlsIjpudWxsLCJwaG9uZSI6IjAxMTEyMjIyMiIsInZlaGljbGVObyI6IkFKUSAzMzMzIiwiZGVwYXJ0bWVudCI6ImZrZWtrIiwiY29tcGFueSI6IkhISCBob2xkaW5nIiwicHVycG9zZSI6Im1lZXRpbmciLCJyb2xlIjoiVmlzaXRvciIsInNlY3VyaXR5IjoiU18xIiwicmVjb3JkcyI6WyJSZWNvcmQwMDEiXSwiaWF0IjoxNjg3NzkxMTk4LCJleHAiOjE2ODc3OTQ3OTh9.gQPKqcWIxYxpwlmSivPYPiizHzVMK_jDG_9YwwTdZ3U
Content-Type: application/json

{   
    "username":"daus",
    "phone": "2000331", 
    "vehicleNo": "AJQ 3333",
    "department": "fkre",
    "company": "HHH holding"
}
###
POST http://localhost:3000/checkIn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTFiODlmZDkwZWFlNzBjNDRmNTUiLCJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IiQyYiQxMCRWc0wxeWpiNGUxSUJicTRPaTlEUnpPVHQzSFFRdmxTTFFabzBISi8yR1E4NXRGcjJlV3JBMiIsIm5hbWUiOiJGaXJkYXVzIiwiaWMiOiIwMjA4MDktMTAtMDMyMyIsImVtYWlsIjpudWxsLCJwaG9uZSI6IjAxMTEyMjIyMiIsInZlaGljbGVObyI6IkFKUSAzMzMzIiwiZGVwYXJ0bWVudCI6ImZrZWtrIiwiY29tcGFueSI6IkhISCBob2xkaW5nIiwicHVycG9zZSI6Im1lZXRpbmciLCJyb2xlIjoiVmlzaXRvciIsInNlY3VyaXR5IjoiU18xIiwicmVjb3JkcyI6W10sImlhdCI6MTY4Nzc2MzQxNywiZXhwIjoxNjg3NzY3MDE3fQ.7zwkvQOUhDHGN1_ss-G40H_J0lh9kk987X6NuMYDFX0
Content-Type: application/json

{
    "recordID":"Record_001",
    "purpose":"Visiting"
}
###
POST http://localhost:3000/checkIn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk0NzQ4YmU0ZTk3YWZkOGYzOTkyMTQiLCJ1c2VybmFtZSI6IlZfMiIsInBhc3N3b3JkIjoiJDJiJDEwJHBGWHV5OXVKd0F4MzRydUNjVVNFZGVCdjh5b1N2R1d6VzVuSGUuWlQ1ZVM1SjE1TlE1eHZLIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDUwNzc0LCJleHAiOjE2ODc0NTQzNzR9.g-5l2vRR-_AOxzQkp8hiLlF4_19eeo1cjbpMtkC2J9Y
Content-Type: application/json

{
    "recordID":"Record_002",
    "purpose":"Meeting"
}

### read for visitor
GET http://localhost:3000/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTFiODlmZDkwZWFlNzBjNDRmNTUiLCJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IiQyYiQxMCRWc0wxeWpiNGUxSUJicTRPaTlEUnpPVHQzSFFRdmxTTFFabzBISi8yR1E4NXRGcjJlV3JBMiIsIm5hbWUiOiJGaXJkYXVzIiwiaWMiOiIwMjA4MDktMTAtMDMyMyIsImVtYWlsIjpudWxsLCJwaG9uZSI6IjAxMTEyMjIyMiIsInZlaGljbGVObyI6IkFKUSAzMzMzIiwiZGVwYXJ0bWVudCI6ImZrZWtrIiwiY29tcGFueSI6IkhISCBob2xkaW5nIiwicHVycG9zZSI6Im1lZXRpbmciLCJyb2xlIjoiVmlzaXRvciIsInNlY3VyaXR5IjoiU18xIiwicmVjb3JkcyI6WyJSZWNvcmQwMDEiXSwiaWF0IjoxNjg3NzkxMTk4LCJleHAiOjE2ODc3OTQ3OTh9.gQPKqcWIxYxpwlmSivPYPiizHzVMK_jDG_9YwwTdZ3U

### read for security
GET http://localhost:3000/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTBkMTFhZGVmYTRiZWNlMjVmZjYiLCJ1c2VybmFtZSI6IlNfMSIsInBhc3N3b3JkIjoiJDJiJDEwJDBYSnYvOEFiOWNSa0JBQkczZDVjbXViNFFkdFFpWTlCMlhUc05PaERCRXZSSTUzNThtbnVTIiwibmFtZSI6IlNlY3VyaXR5MSIsImVtYWlsIjoiU2VjdXJpdHlxQGdtYWlsLmNvbSIsInJvbGUiOiJTZWN1cml0eSIsInZpc2l0b3JzIjpbImRhdXMiLCJkYXVzIl0sImlhdCI6MTY4Nzc5MTE2MywiZXhwIjoxNjg3Nzk0NzYzfQ.vOQJddpLJyOssecdn6ehlLY8DgDGvahSDDilooJj3RA

### read for admin
GET http://localhost:3000/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTBkMTFhZGVmYTRiZWNlMjVmZjYiLCJ1c2VybmFtZSI6IlNfMSIsInBhc3N3b3JkIjoiJDJiJDEwJDBYSnYvOEFiOWNSa0JBQkczZDVjbXViNFFkdFFpWTlCMlhUc05PaERCRXZSSTUzNThtbnVTIiwibmFtZSI6IlNlY3VyaXR5MSIsImVtYWlsIjoiU2VjdXJpdHlxQGdtYWlsLmNvbSIsInJvbGUiOiJTZWN1cml0eSIsInZpc2l0b3JzIjpbImRhdXMiLCJkYXVzIl0sImlhdCI6MTY4Nzc5MTE2MywiZXhwIjoxNjg3Nzk0NzYzfQ.vOQJddpLJyOssecdn6ehlLY8DgDGvahSDDilooJj3RA


###
PATCH http://localhost:3000/checkOut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTFiODlmZDkwZWFlNzBjNDRmNTUiLCJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IiQyYiQxMCRWc0wxeWpiNGUxSUJicTRPaTlEUnpPVHQzSFFRdmxTTFFabzBISi8yR1E4NXRGcjJlV3JBMiIsIm5hbWUiOiJGaXJkYXVzIiwiaWMiOiIwMjA4MDktMTAtMDMyMyIsImVtYWlsIjpudWxsLCJwaG9uZSI6IjAxMTEyMjIyMiIsInZlaGljbGVObyI6IkFKUSAzMzMzIiwiZGVwYXJ0bWVudCI6ImZrZWtrIiwiY29tcGFueSI6IkhISCBob2xkaW5nIiwicHVycG9zZSI6Im1lZXRpbmciLCJyb2xlIjoiVmlzaXRvciIsInNlY3VyaXR5IjoiU18xIiwicmVjb3JkcyI6W10sImlhdCI6MTY4Nzc2MzQxNywiZXhwIjoxNjg3NzY3MDE3fQ.7zwkvQOUhDHGN1_ss-G40H_J0lh9kk987X6NuMYDFX0


###
PATCH http://localhost:3000/checkOut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk0NzQ4YmU0ZTk3YWZkOGYzOTkyMTQiLCJ1c2VybmFtZSI6IlZfMiIsInBhc3N3b3JkIjoiJDJiJDEwJHBGWHV5OXVKd0F4MzRydUNjVVNFZGVCdjh5b1N2R1d6VzVuSGUuWlQ1ZVM1SjE1TlE1eHZLIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDUwNzc0LCJleHAiOjE2ODc0NTQzNzR9.g-5l2vRR-_AOxzQkp8hiLlF4_19eeo1cjbpMtkC2J9Y

###delete user by checking token
DELETE http://localhost:3000/deleteVisitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDk4YTFiODlmZDkwZWFlNzBjNDRmNTUiLCJ1c2VybmFtZSI6ImRhdXMiLCJwYXNzd29yZCI6IiQyYiQxMCRWc0wxeWpiNGUxSUJicTRPaTlEUnpPVHQzSFFRdmxTTFFabzBISi8yR1E4NXRGcjJlV3JBMiIsIm5hbWUiOiJGaXJkYXVzIiwiaWMiOiIwMjA4MDktMTAtMDMyMyIsImVtYWlsIjpudWxsLCJwaG9uZSI6IjIwMDAzMzEiLCJ2ZWhpY2xlTm8iOiJBSlEgMzMzMyIsImRlcGFydG1lbnQiOiJma3JlIiwiY29tcGFueSI6IkhISCBob2xkaW5nIiwicHVycG9zZSI6Im1lZXRpbmciLCJyb2xlIjoiVmlzaXRvciIsInNlY3VyaXR5IjoiU18xIiwicmVjb3JkcyI6WyJSZWNvcmQwMDEiXSwiaWF0IjoxNjg3ODA0MzQxLCJleHAiOjE2ODc4MDc5NDF9.iPOkjuUC63Tx0OwGC26JVpjuwqGUwgPw3VVa-qE-usg


